### ISSUE TITLE
'Could not resolve module' output on startup

### ISSUE THREAD

**Issue by rage5474** [Elektrobit/eb-solys#10]
!ENTRY org.eclipse.birt.chart.device.pdf 4 0 2018-10-30 13:55:18.937
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.birt.chart.device.pdf [470]
  Unresolved requirement: Require-Bundle: org.apache.batik.util; bundle-version="[1.6.0,1.7.0)"
  Unresolved requirement: Require-Bundle: org.apache.batik.pdf; bundle-version="[1.6.0,1.7.0)"
    -> Bundle-SymbolicName: org.apache.batik.pdf; bundle-version="1.6.0.v201105071520"
       org.apache.batik.pdf [437]
         Unresolved requirement: Import-Package: org.apache.batik.bridge; version="[1.6.0,1.7.0)"
           -> Export-Package: org.apache.batik.bridge; bundle-symbolic-name="org.apache.batik.bridge"; bundle-version="1.6.0.v201011041432"; version="1.6.0"
              org.apache.batik.bridge [427]
                Unresolved requirement: Require-Bundle: org.apache.batik.css; bundle-version="[1.6.0,1.7.0)"
  Unresolved requirement: Require-Bundle: org.apache.batik.transcoder; bundle-version="[1.6.0,1.7.0)"
    -> Bundle-SymbolicName: org.apache.batik.transcoder; bundle-version="1.6.0.v201011041432"
       org.apache.batik.transcoder [441]
         Unresolved requirement: Require-Bundle: org.apache.batik.util; bundle-version="[1.6.0,1.7.0)"
         Unresolved requirement: Require-Bundle: org.apache.batik.svggen; bundle-version="[1.6.0,1.7.0)"
           -> Bundle-SymbolicName: org.apache.batik.svggen; bundle-version="1.6.0.v201011041432"
              org.apache.batik.svggen [439]
                Unresolved requirement: Require-Bundle: org.apache.batik.ext.awt; bundle-version="[1.6.0,1.7.0)"
                  -> Bundle-SymbolicName: org.apache.batik.ext.awt; bundle-version="1.6.0.v201011041432"
                     org.apache.batik.ext.awt [434]
                       Unresolved requirement: Require-Bundle: org.apache.batik.util; bundle-version="[1.6.0,1.7.0)"
         Unresolved requirement: Require-Bundle: org.apache.batik.bridge; bundle-version="[1.6.0,1.7.0)"
           -> Bundle-SymbolicName: org.apache.batik.bridge; bundle-version="1.6.0.v201011041432"
         Unresolved requirement: Require-Bundle: org.apache.batik.dom; bundle-version="[1.6.0,1.7.0)"
           -> Bundle-SymbolicName: org.apache.batik.dom; bundle-version="1.6.1.v201505192100"
              org.apache.batik.dom [432]
                Unresolved requirement: Import-Package: org.apache.xerces.parsers; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.apache.batik.css; bundle-version="[1.6.0,1.7.0)"
         Unresolved requirement: Require-Bundle: org.apache.batik.dom.svg; bundle-version="[1.6.0,1.7.0)"
           -> Bundle-SymbolicName: org.apache.batik.dom.svg; bundle-version="1.6.0.v201011041432"
              org.apache.batik.dom.svg [431]
                Unresolved requirement: Require-Bundle: org.apache.batik.css; bundle-version="[1.6.0,1.7.0)"
         Unresolved requirement: Require-Bundle: org.apache.batik.ext.awt; bundle-version="[1.6.0,1.7.0)"
           -> Bundle-SymbolicName: org.apache.batik.ext.awt; bundle-version="1.6.0.v201011041432"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1536)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.emf.mapping.ecore2ecore 4 0 2018-10-30 13:55:18.941
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.emf.mapping.ecore2ecore [542]
  Unresolved requirement: Require-Bundle: org.eclipse.emf.ecore.edit; bundle-version="[2.9.0,3.0.0)"; visibility:="reexport"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1536)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.equinox.p2.transport.ecf 4 0 2018-10-30 13:55:18.943
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.p2.transport.ecf [597]
  Unresolved requirement: Require-Bundle: org.eclipse.ecf; bundle-version="3.1.0"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1536)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.linuxtools.dataviewers.charts 4 0 2018-10-30 13:55:18.946
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.linuxtools.dataviewers.charts [659]
  Unresolved requirement: Require-Bundle: org.eclipse.linuxtools.dataviewers; bundle-version="4.0.0"
    -> Bundle-SymbolicName: org.eclipse.linuxtools.dataviewers; bundle-version="6.1.0.201809272014"; singleton:="true"
       org.eclipse.linuxtools.dataviewers [662]
         Unresolved requirement: Require-Bundle: org.eclipse.linuxtools.binutils

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1536)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.linuxtools.dataviewers 4 0 2018-10-30 13:55:18.949
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.linuxtools.dataviewers [662]
  Unresolved requirement: Require-Bundle: org.eclipse.linuxtools.binutils

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1536)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.tracecompass.tmf.analysis.xml.ui 4 0 2018-10-30 13:55:18.952
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.tracecompass.tmf.analysis.xml.ui [759]
  Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.ui

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1536)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.tracecompass.tmf.ui 4 0 2018-10-30 13:55:18.955
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.tracecompass.tmf.ui [766]
  Another singleton bundle selected: osgi.identity; osgi.identity="org.eclipse.tracecompass.tmf.ui"; type="osgi.bundle"; version:Version="2.2.0.qualifier"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1536)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.xtend.typesystem.emf.ui 4 0 2018-10-30 13:55:18.958
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtend.typesystem.emf.ui [814]
  Unresolved requirement: Require-Bundle: org.eclipse.xtend.shared.ui

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1536)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.xtext.ui.ecore 4 0 2018-10-30 13:55:18.963
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.xtext.ui.ecore [869]
  Unresolved requirement: Require-Bundle: org.eclipse.emf.ecore.editor; bundle-version="2.10.0"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1536)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

**Comment by rage5474** [comment]
Solved by other issue.

**Comment by phandung95** [comment]
Could u pls give me the solution. I am getting the same trouble and I can't resolve this issue ! Tks u so much.

**Comment by raphael-systemticks** [comment]
Do you face this issue with EB solys or with your own application?

**Comment by phandung95** [comment]
sr, exactly, when I ran RapidClipse application.

**Comment by raphael-systemticks** [comment]
Then you should ask your question here: http://www.rapidclipse.com/en/forum/index.php/forum/forum-english
Because the issue can only be solved if the missing dependencies will be fixed. So there is no general solution.

**Comment by phandung95** [comment]
tks for ur answer, I tried to find the solution but forgot the way that u said. :)
