### ISSUE TITLE
Scripting not working for MacOS

### ISSUE THREAD

**Issue by surrender70** [Elektrobit/eb-solys#19]
!STACK 0
java.lang.NullPointerException
        at com.elektrobit.ebrace.core.scriptimporter.impl.project.ClasspathFileCreator.getJVMPath(ClasspathFileCreator.java:81)
        at com.elektrobit.ebrace.core.scriptimporter.impl.project.ClasspathFileCreator.createClasspath(ClasspathFileCreator.java:33)
        at com.elektrobit.ebrace.core.scriptimporter.impl.project.ScriptProjectImporter.updateClasspathFile(ScriptProjectImporter.java:138)
        at com.elektrobit.ebrace.core.scriptimporter.impl.project.ScriptProjectImporter.importProject(ScriptProjectImporter.java:59)

**Comment by surrender70** [comment]
Locally fixed:
For macOS the plugin org.eclipse.jdt.launching.macosx needs to be added to the product configuration
